TestPattern:
  type: random # Choose: random, vecfile, exhaustive, specific
  numrandom: 10
  seed: 2435432
  pattern: "11111111"
  bpdelay: 10 #(B)etween (P)ulse delay (measured in clock cycles)
  acdelay: 10 #(A)fter (C)lock delay (measured in timesteps)
Files:
  vecfilepath: /home/edrich/github/pygentb/examples/ksa4/testpattern.vec
  toppath: /home/edrich/github/pygentb/examples/ksa4/ksa4.v
  outpath: build
TestbenchParams:
  clockname: clk
  timescale: 1ps/100fs
  clkperiod: 40
  simlength: 10000