[Ports]
sequence    =   ["A0","B0","SUM0","SUM1","SUM2","SUM3","COUT","A1","A2","A3","B1","B2","B3","CIN","clk"]
inputs      =   ["A0","B0","A1","A2","A3","B1","B2","B3","CIN"]
outputs     =   ["SUM0","SUM1","SUM2","SUM3"]
clockname   =   "clk"

[TestPattern]
exhaustive  =   false
usevecfile  =   true
vecfilepath =   "./examples/testpattern.vec"
pattern     =   [ "00", "01", "10", "11" ]
bpdelay     =   10 #(B)etween (P)ulse delay
acdelay     =   10 #(A)fter (C)lock delay

[Files]
toppath     =   "./examples/ksa4.v"
outdirpath  =   "build"

[TestbenchParams]
tbname      =   "Testbench"
topname     =   "KSA4"
timescale   =   "1ps/100fs"
clkperiod   =   40
simlength   =   10000